[tool.pylint."messages control"]
disable = ["raw-checker-failed", "bad-inline-option", "locally-disabled", "file-ignored", "suppressed-message", "useless-suppression", "deprecated-pragma", "use-implicit-booleaness-not-comparison-to-string", "use-implicit-booleaness-not-comparison-to-zero", "use-symbolic-message-instead", "missing-module-docstring", "missing-class-docstring", "missing-function-docstring", "unidiomatic-typecheck", "comparison-with-itself", "duplicate-code", "too-many-ancestors", "too-few-public-methods", "abstract-method", "fixme"]

[mypy]
check_untyped_defs = true
